import React from 'react';
import Head from 'next/head';

export interface ILayoutProps {
  title: string;
  children: React.ReactNode;
}

const Layout = ({ title, children }: ILayoutProps) => {
  return (
    <div>
      <Head>
        <title>{title} | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mx-auto`}>{children}</main>
    </div>
  );
};

export default Layout;
